image:
  repository: container-registry-k8s-cmc.khacthienit.click/hotelmanagerment/hotel-backend
  tag:
imagePullSecrets:
- name: dockerhub-secret
deployments:
- name: hotel-backend
  replicasCount: 1
  # nodeSelector:
  #   kubernetes.io/arch: arm64
  prometheusEnabled: false
  service:
    name: hotel-backend
    HTTPPort: 4000
    health:
      live: "/health"
      ready: "/health"
      initialDelaySeconds: 60
      periodSeconds: 10
      failureThreshold: 5
      timeoutSeconds: 3
env:
  ENV: prod
envFrom:
    - configMapRef:
        name: hotel-backend-env
ingress:
  enabled: true
  plugins: []
  ingressClassName: nginx
  annotations:
    # kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    cert-manager.io/cluster-issuer: letsencrypt-dns
  tls:
  - hosts:
      - hotel-backend.project3cloudinus.click
    secretName: hotel-backend-tls
  rules:
  - host: hotel-backend.project3cloudinus.click
    paths:
    - path: /
      servicePort: 80
      serviceName: hotel-backend
resources:
  # requests:
  #   cpu: "500m"
  #   memory: "1Gi"
  limits:
    cpu: "4"
    memory: "4500Mi"
infisical:
  enabled: false
